/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JForm;

import BLL.CTHoaDonBLL;
import BLL.HoaDonBLL;
import BLL.LoaiMonAnBLL;
import BLL.MonAnBLL;
import BLL.PhieuGiamGiaBLL;
import BLL.ThanhVienBLL;
import DTO.MonAnDTO; 
import DTO.PhieuGiamGiaDTO;
import DTO.ThanhVienDTO;
import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.ComboBoxModel;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author mizuk
 */
public class ManageForm extends javax.swing.JFrame {

    DefaultTableModel model = null;
    DefaultTableModel model_1 = null;
    DefaultComboBoxModel modelCbx = null;
    
    private static int ma_tk;
    private static String ma_nv;
    private static int ma_quyen;
    public static String ma_thanh_vien = null;
    public static int diem = 0;
    public static int giam_theo_ma = 0;
    public static int giam_theo_diem = 0;
    public static String ma_phieu_giam = null;
    
    public  ManageForm(){
    }
    
    public ManageForm(String ma_nv, int ma_quyen, int ma_tk) {
        this.ma_tk = ma_tk;
        this.ma_nv = ma_nv;
        this.ma_quyen = ma_quyen;
        
        setResizable(false);
        initComponents();
        
        initTitleTableFood();
        initTitleTableBillInfo();
        setCategoryToComboBox();
        setSpinnerDiem();
    }
    
    //set-get
    // <editor-fold defaultstate="collapsed" desc="Generated Code">  
    public static String getMa_thanh_vien() {
        return ma_thanh_vien;
    }

    public static void setMa_thanh_vien(String ma_thanh_vien) {
        ManageForm.ma_thanh_vien = ma_thanh_vien;
    }

    public static String getMa_nv() {
        return ma_nv;
    }

    public static void setMa_nv(String ma_nv) {
        ManageForm.ma_nv = ma_nv;
    }
    
    public static int getMaQuyen() {
        return ma_quyen;
    }

    public static void setMaQuyen(int ma_quyen) {
        ManageForm.ma_quyen = ma_quyen;
    }
    // </editor-fold>
    
    private void initTitleTableFood(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã món","Tên món","Giá","Số lượng còn"
        });
        tblFoodManage.setModel(model);
    }
    private void initTitleTableBillInfo(){
        model_1 = new DefaultTableModel();
        model_1.setColumnIdentifiers(new String[]{
            "Mã món","Tên món","Giá","Số lượng","Thành tiền"
        });
        tblInfobill.setModel(model_1);
    }
    private  void setCategoryToComboBox(){
        modelCbx = new DefaultComboBoxModel();
        new LoaiMonAnBLL().setTenLoaiToComboBox(modelCbx);
        cbxCategory.setModel(modelCbx);
    }
    
    private void tinhtong(){
        int tong = 0;
        for(int i = 0 ; i < model_1.getRowCount() ; i++){
            tong += (int) model_1.getValueAt(i, 4);
        }
        lblTotalPrice.setText(String.valueOf(tong));
    }
    public void setGiaThanhToan(){
        int tong_giam = giam_theo_diem + giam_theo_ma;
        lblGiam.setText(String.valueOf(tong_giam));

        int gia_goc = Integer.parseInt(lblTotalPrice.getText());
        int gia_sau_cung = gia_goc - tong_giam;
        lblTotalPriceAfter.setText(String.valueOf(gia_sau_cung));
    }
    private void setSpinnerDiem(){
        SpinnerModel spinnerModel = new SpinnerNumberModel(
            0,0,0,0
        );
        spnDiem.setModel(spinnerModel);
    }
    private void sauKhiThanhToan(){
        ma_phieu_giam = null;
        ma_thanh_vien = null;
        giam_theo_diem = 0;
        giam_theo_ma = 0;
        diem = 0;
        setSpinnerDiem();
        //cập nhật model_1
        while(model_1.getRowCount() > 0){
            model_1.removeRow(0);
        }
        //cập nhật model
        String ten_loai = (String) cbxCategory.getSelectedItem();
        String ma_loai = new LoaiMonAnBLL().getMaLoaiByTenLoai(ten_loai);
        new MonAnBLL().setListFoodByMaLoai(model,ma_loai);
        
        lblGiam.setText("");
        lblTotalPrice.setText("");
        lblTotalPriceAfter.setText("");
    }
                       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAddFood = new javax.swing.JButton();
        spnCount = new javax.swing.JSpinner();
        cbxCategory = new javax.swing.JComboBox<>();
        btnXoaMon = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTotalPrice = new javax.swing.JLabel();
        lblGiam = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblTotalPriceAfter = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtMaGiamGia = new javax.swing.JTextField();
        btnXacNhanMa = new javax.swing.JButton();
        txtMaTV = new javax.swing.JTextField();
        btnXacNhanTV = new javax.swing.JButton();
        btnDangKytv = new javax.swing.JButton();
        spnDiem = new javax.swing.JSpinner();
        btnChitiet = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbxbuocNhay = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFoodManage = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInfobill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAdmin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnSuaTk = new javax.swing.JMenuItem();
        nmLogout = new javax.swing.JMenuItem();

        setTitle("Quản lý bán hàng");

        btnAddFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_30px.png"))); // NOI18N
        btnAddFood.setText("Thêm món");
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });

        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCategory.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại món"));
        cbxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoryActionPerformed(evt);
            }
        });

        btnXoaMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_30px_1.png"))); // NOI18N
        btnXoaMon.setText("Xóa món");
        btnXoaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddFood, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaMon)
                .addGap(6, 6, 6)
                .addComponent(spnCount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxCategory)
                    .addComponent(btnAddFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnCount))
                .addContainerGap())
        );

        lblTotalPrice.setBackground(new java.awt.Color(153, 153, 255));
        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPrice.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng tiền"));

        lblGiam.setBackground(new java.awt.Color(153, 153, 255));
        lblGiam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiam.setBorder(javax.swing.BorderFactory.createTitledBorder("Giảm"));

        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thanhtoan-30.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xemchitiet-30.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblTotalPriceAfter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPriceAfter.setBorder(javax.swing.BorderFactory.createTitledBorder("Phải thanh toán"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPriceAfter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblTotalPriceAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMaGiamGia.setBorder(javax.swing.BorderFactory.createTitledBorder("Voucher"));

        btnXacNhanMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_ok_30px.png"))); // NOI18N
        btnXacNhanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanMaActionPerformed(evt);
            }
        });

        txtMaTV.setBorder(javax.swing.BorderFactory.createTitledBorder("Mã thành viên"));

        btnXacNhanTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_ok_30px.png"))); // NOI18N
        btnXacNhanTV.setText("Xác nhận");
        btnXacNhanTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanTVActionPerformed(evt);
            }
        });

        btnDangKytv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_circled_user_male_30px.png"))); // NOI18N
        btnDangKytv.setText("Đăng ký");
        btnDangKytv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKytvActionPerformed(evt);
            }
        });

        spnDiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Điểm"));

        btnChitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-male-30.png"))); // NOI18N
        btnChitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChitietActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_refresh_30px.png"))); // NOI18N
        jButton4.setText("Đổi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbxbuocNhay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "500", "1000", "2000", "5000" }));
        cbxbuocNhay.setBorder(javax.swing.BorderFactory.createTitledBorder("bước nhảy"));
        cbxbuocNhay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxbuocNhayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnXacNhanTV, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDangKytv, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbxbuocNhay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXacNhanMa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhanMa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaTV)
                    .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXacNhanTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangKytv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxbuocNhay)
                    .addComponent(spnDiem)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblFoodManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFoodManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFoodManageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFoodManage);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        tblInfobill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblInfobill);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Hóa đơn");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jMenu1.setText("Admin");

        mnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_client_company_30px.png"))); // NOI18N
        mnAdmin.setText("Admin");
        mnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdminActionPerformed(evt);
            }
        });
        jMenu1.add(mnAdmin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Thông tin tài khoản");

        mnSuaTk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_circled_user_male_30px.png"))); // NOI18N
        mnSuaTk.setText("Thông tin tài khoản");
        mnSuaTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuaTkActionPerformed(evt);
            }
        });
        jMenu2.add(mnSuaTk);

        nmLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_exit_30px.png"))); // NOI18N
        nmLogout.setText("Đăng xuất");
        nmLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(nmLogout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSuaTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuaTkActionPerformed
        new AccountForm(ma_tk).setVisible(true);
    }//GEN-LAST:event_mnSuaTkActionPerformed

    private void mnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdminActionPerformed
        if(ma_quyen == 1){
            new AdminForm().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Không đủ quyền truy cập\nNhân viên thì lo làm \nVào đây phá hay gì ?","Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_mnAdminActionPerformed
    
    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed

        int select = tblFoodManage.getSelectedRow();
        if(select >= 0){
            int soLuongMua = (int) spnCount.getValue();
            String maMon  = (String) tblFoodManage.getValueAt(select, 0);
            if(model_1.getRowCount() == 0){
                MonAnDTO monAnDTO = new MonAnBLL().getFoodByMaMon(maMon);
                model_1.addRow(new Object[]{
                    monAnDTO.getMa_mon(),
                    monAnDTO.getTen_mon(),
                    monAnDTO.getGia(),
                    soLuongMua,
                    (int)(monAnDTO.getGia()*soLuongMua)
                });
                model_1.fireTableDataChanged();
                
                tinhtong();
                setGiaThanhToan();
            }
            else{
                for(int i = 0 ; i < model_1.getRowCount() ; i++){
                    if(model_1.getValueAt(i, 0).equals(maMon)){
                        int soluong = ((int) model_1.getValueAt(i,3)+ soLuongMua);
                        int thanhtien = (int)(model_1.getValueAt(i,2))*soluong;
                        model_1.setValueAt(soluong, i,3);
                        model_1.setValueAt(thanhtien, i,4);
                        model_1.fireTableDataChanged();
                        
                        tinhtong();
                        setGiaThanhToan();
                        
                        int soLuongConLai = ((int)model.getValueAt(select,3)-(int)model_1.getValueAt(i,3));
                        int soLuongTru = (int)model_1.getValueAt(i,3);
                        System.out.println(soLuongConLai);
                        SpinnerModel spinnerModel = new SpinnerNumberModel(
                            soLuongConLai == 0 ? 0 : 1,
                            0-soLuongTru,
                            soLuongConLai,
                            1);
                        spnCount.setModel(spinnerModel);
                        if((int)model_1.getValueAt(i,3) == 0){
                            model_1.removeRow(i);
                        }
                        return;
                    }
                }
                MonAnDTO monAnDTO = new MonAnBLL().getFoodByMaMon(maMon);
                model_1.addRow(new Object[]{
                    monAnDTO.getMa_mon(),
                    monAnDTO.getTen_mon(),
                    monAnDTO.getGia(),
                    soLuongMua,
                    (int)(soLuongMua*monAnDTO.getGia())
                });
                model_1.fireTableDataChanged();
                
                tinhtong();
                setGiaThanhToan();
            }
            for(int i = 0; i < model_1.getRowCount(); i++){
                if(model_1.getValueAt(i,0).equals(maMon)){
                    int soLuongConLai = ((int)model.getValueAt(select,3)-(int)model_1.getValueAt(i,3));
                    int soLuongTru = (int)model_1.getValueAt(i,3);
                    System.out.println(soLuongConLai);
                    SpinnerModel spinnerModel = new SpinnerNumberModel(
                        soLuongConLai == 0 ? 0 : 1,
                        0-soLuongTru,
                        soLuongConLai,
                        1);
                    spnCount.setModel(spinnerModel);
                    if((int)model_1.getValueAt(i,3) == 0){
                        model_1.removeRow(i);
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnAddFoodActionPerformed

    private void tblFoodManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFoodManageMouseClicked
        int select = tblFoodManage.getSelectedRow();
        if(select >= 0){
            String maMon = (String) tblFoodManage.getValueAt(select, 0);
            int countFood = new MonAnBLL().getCountFood(maMon);
            
            for(int i = 0; i < model_1.getRowCount();i++){
                if(model_1.getValueAt(i,0).equals(maMon)){
                    if((int)model.getValueAt(select,3) >= (int)model_1.getValueAt(i,3)){
                        int soLuongConLai = (int)model.getValueAt(select,3) - (int)model_1.getValueAt(i, 3);
                        int soLuongTru = (int)model_1.getValueAt(i,3);
                        SpinnerModel spinnerModel = new SpinnerNumberModel(
                            soLuongConLai == 0 ? 0 : 1,
                            (0-soLuongTru),
                            soLuongConLai,
                            1);
                        spnCount.setModel(spinnerModel);
                        return;
                    }
                }
            }
            SpinnerModel spinnerModel = new SpinnerNumberModel(1, // initial value
                1, // min
                countFood, // max
                1);// step
            spnCount.setModel(spinnerModel);  
        }
    }//GEN-LAST:event_tblFoodManageMouseClicked

    public void loadTableManager(String ma_loai){
        new MonAnBLL().setListFoodByMaLoai(model,ma_loai);
    }
    private void cbxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoryActionPerformed
        
        String ten_loai = (String) cbxCategory.getSelectedItem();
        
        String ma_loai = new LoaiMonAnBLL().getMaLoaiByTenLoai(ten_loai);
        
        new MonAnBLL().setListFoodByMaLoai(model,ma_loai);
    }//GEN-LAST:event_cbxCategoryActionPerformed

    private void nmLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmLogoutActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Bạn có thật sự muốn đăng xuất?","Thông báo",JOptionPane.YES_OPTION) == 0){
            ManageForm.setMa_nv(null);
            ManageForm.setMaQuyen(0);
            this.setVisible(false);
        }
    }//GEN-LAST:event_nmLogoutActionPerformed

    private void btnXoaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonActionPerformed
        int click = tblInfobill.getSelectedRow();
        if(click >= 0){
            String ma_sp = String.valueOf(tblInfobill.getValueAt(click,0));
            int totalPrice = Integer.parseInt(lblTotalPrice.getText());
            int giaSpXoa = (int) tblInfobill.getValueAt(click,2);
            int gia_giam = Integer.parseInt(lblGiam.getText());
            lblTotalPrice.setText(String.valueOf((totalPrice-giaSpXoa)));
            lblTotalPriceAfter.setText(String.valueOf(totalPrice-giaSpXoa-gia_giam));
            model_1.removeRow(click);
            
        }
    }//GEN-LAST:event_btnXoaMonActionPerformed

    private void btnDangKytvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKytvActionPerformed
        new DangKyThanhVienForm().setVisible(true);
    }//GEN-LAST:event_btnDangKytvActionPerformed

    private void btnXacNhanTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanTVActionPerformed
        String ma_tv = txtMaTV.getText();
        if(new ThanhVienBLL().checkMaThanhVien(ma_tv)){
            String mat_khau = JOptionPane.showInputDialog(this,"Mã xác nhận (mật khẩu):","Yêu cầu nhập mật khẩu",JOptionPane.INFORMATION_MESSAGE);
            if(new ThanhVienBLL().checkMatKhau(mat_khau)){
                
                //lưu ma thành viên vào piến static
                ma_thanh_vien = ma_tv;
                txtMaTV.setText(ma_thanh_vien);
                
                //form thanh vien
                new ThanhVienForm(ma_thanh_vien).setVisible(true);
                
                //thiết lập điểm theo mã thành viên
                ThanhVienDTO thanhVienDTO = new ThanhVienBLL().getTvByMaTV(ma_thanh_vien);
                diem =thanhVienDTO.getPoint();
                int buocNhay = Integer.parseInt((String)cbxbuocNhay.getSelectedItem());
                SpinnerModel spinnerModel = new SpinnerNumberModel(
                        0,0,diem,buocNhay
                );
                spnDiem.setModel(spinnerModel);
            }
            else{
                JOptionPane.showMessageDialog(this,"Sai mật khẩu","Sai thông tin",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Mã thành viên không đúng", "Sai thông tin",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXacNhanTVActionPerformed

    private void btnChitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChitietActionPerformed
//        System.out.println(ma_thanh_vien);
        if(ma_thanh_vien != null){
            if(new ThanhVienBLL().checkMaThanhVien(ma_thanh_vien)){
                new ThanhVienForm(ma_thanh_vien).setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Chưa xác nhận mã thành viên","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_btnChitietActionPerformed

    private void cbxbuocNhayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxbuocNhayActionPerformed
        int buocNhay = Integer.parseInt((String)cbxbuocNhay.getSelectedItem());
        System.out.println(buocNhay);
        int diem_hien_tai = (int) spnDiem.getValue();
        SpinnerModel spinnerModel = new SpinnerNumberModel(diem_hien_tai,0,diem,buocNhay);
        spnDiem.setModel(spinnerModel);
    }//GEN-LAST:event_cbxbuocNhayActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(tblInfobill.getRowCount() == 0){
            JOptionPane.showMessageDialog(this,"Chưa mua sản phẩm "
                    + "\nKhông thể đổi điểm", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int diem_doi = (int)spnDiem.getValue();
            giam_theo_diem = diem_doi;
            
            setGiaThanhToan();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnXacNhanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanMaActionPerformed
        String ten_giam_gia = txtMaGiamGia.getText();
        if(tblInfobill.getRowCount() > 0){
            if(ma_phieu_giam != null){
                JOptionPane.showMessageDialog(this,"Chỉ được sử dụng 1 Voucher cho một hóa đơn","Lỗi",JOptionPane.ERROR_MESSAGE);
                return;
            }
            PhieuGiamGiaDTO phieuGiamGiaDTO = new PhieuGiamGiaBLL().getPGGbyTenPGG(ten_giam_gia);
//            System.out.println(phieuGiamGiaDTO);
            if(phieuGiamGiaDTO != null){
                if(new PhieuGiamGiaBLL().checkDate(phieuGiamGiaDTO)){
                    if(phieuGiamGiaDTO.getTrang_thai() == 1){
                        int kq = JOptionPane.showConfirmDialog(this,"Mỗi mã chỉ sử dụng được một lần \nBạn có thật sự muốn sử dụng mã này","Thông páo",JOptionPane.YES_OPTION);
//                        System.out.println(kq);
                        if(kq == 0){
//                        System.out.println(phieuGiamGiaDTO);
                        giam_theo_ma = phieuGiamGiaDTO.getGiam();
                        setGiaThanhToan();
                        ma_phieu_giam = phieuGiamGiaDTO.getMa_phieu_giam_gia();
                        new PhieuGiamGiaBLL().updateTrangThai(ma_phieu_giam);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Voucher đã được sử dụng","Lỗi",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Phiếu đã hết hạn sử dụng","Lỗi",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Không tồn tại hoặc sai Voucher","Lỗi",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Chưa có sản phẩm nào được chọn","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnXacNhanMaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(this,("Giảm từ điểm: "+giam_theo_diem+" Đ"
                + "\nGiảm theo mã: "+giam_theo_ma+" Đ"),"Chi tiết giảm",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        int kq = JOptionPane.showConfirmDialog(this,"Xác nhận thanh toán","Thông báo", JOptionPane.YES_OPTION);
        if(kq ==0){
            HoaDonBLL hdbll = new HoaDonBLL();
            CTHoaDonBLL cthdbll = new CTHoaDonBLL();

            long millis=System.currentTimeMillis(); 
            Date date = new Date(millis);

            String ma_hd = "HD"+hdbll.MaMoi();
            String[] hd = {
                ma_hd,//arr[0]
                ma_nv,//arr[1]
                ma_thanh_vien,//arr[2],
                lblTotalPrice.getText(),//arr[3]
                lblGiam.getText(),//arr[4]
                lblTotalPriceAfter.getText(),//arr[5]
                ma_phieu_giam,//arr[6]
                String.valueOf(giam_theo_diem),//arr[7]
                date.toString(),//arr[8]
            };
            hdbll.CreateHD(hd);
            cthdbll.taoCTHoaDonToHoaDon(model_1, ma_hd);

            int tong_tien = Integer.parseInt(lblTotalPrice.getText());
            if(ma_thanh_vien != null){
                if(tong_tien > 10000){
                    String []thanhVien = {
                        ma_thanh_vien,
                        String.valueOf(tong_tien*0.1)
                    };
                    new  ThanhVienBLL().capNhatDiemTichLuy(thanhVien);
                }
            }
            JOptionPane.showMessageDialog(this,("Thông tin hóa đơn \nMã hóa đơn: "+ma_hd+"\n"
                    + "Mã thành viên: "+ma_thanh_vien+"\n"
                    + "Nhân viên thanh toán: "+ma_nv+"\n"
                    + "Ngày: "+date.toString()+"\n"
                    + "Tổng tiền: "+lblTotalPrice.getText()+" Đ\n"
                    + "Tiền giảm: "+lblGiam.getText()+" Đ\n"
                    + "Phải thanh toán: "+lblTotalPriceAfter.getText()+" Đ\n"
                    + "Điểm tích lũy được: "+(int)(tong_tien*0.1)),"Thông tin hóa đơn",JOptionPane.INFORMATION_MESSAGE);

            sauKhiThanhToan();
        }
        
    }//GEN-LAST:event_btnThanhToanActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("FlatLaf Dark".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        try {
        UIManager.setLookAndFeel(new FlatDarkLaf());
//</editor-fold>
//</editor-fold>
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ManageForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageForm(ma_nv,ma_quyen,ma_tk).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnChitiet;
    private javax.swing.JButton btnDangKytv;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXacNhanMa;
    private javax.swing.JButton btnXacNhanTV;
    private javax.swing.JButton btnXoaMon;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxbuocNhay;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGiam;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTotalPriceAfter;
    private javax.swing.JMenuItem mnAdmin;
    private javax.swing.JMenuItem mnSuaTk;
    private javax.swing.JMenuItem nmLogout;
    private javax.swing.JSpinner spnCount;
    private javax.swing.JSpinner spnDiem;
    private javax.swing.JTable tblFoodManage;
    private javax.swing.JTable tblInfobill;
    private javax.swing.JTextField txtMaGiamGia;
    private javax.swing.JTextField txtMaTV;
    // End of variables declaration//GEN-END:variables

}
