/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */ 
package JForm;
import BLL.CTChuongTrinhKMBLL;
import DTO.CTChuongTrinhKMDTO;
import BLL.LoaiMonAnBLL;
import BLL.MonAnBLL;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niek
 */
public class CtkmForm extends javax.swing.JFrame {

    CTChuongTrinhKMBLL cTChuongTrinhKMBLL = new CTChuongTrinhKMBLL();
    LoaiMonAnBLL loaiMonAnBLL = new LoaiMonAnBLL();
    MonAnBLL monAnBLL = new MonAnBLL();
    
    DefaultTableModel model = null;
    DefaultComboBoxModel<String> model_1 = null;
    DefaultComboBoxModel<String> model_2 = null;
    
    private static int ma_ctkm;
    private static String ten_ctkm = null;
    private static int trang_thai;
    
    public CtkmForm(int ma_ctkm,String ten_ctkm,int trang_thai){
        this.ma_ctkm = ma_ctkm;
        this.ten_ctkm = ten_ctkm;
        this.trang_thai = trang_thai;
        
        setLocationRelativeTo(null);
        setResizable(false);
        initComponents();
        initTableCTCTKM();
        
        lblMaCTKM.setText(ma_ctkm +"");
        lblTenCTKM.setText(ten_ctkm);
        
        loadTableCTCTKM();
        loadComboboxLoai();
        loadComboboxMon("LM01");
    }
    public int getMaCTKM(){
        return this.ma_ctkm;
    }
    public String getTenCTKM(){
        return this.ten_ctkm;
    }
//    public int setMaCTKM(int ma_ctkm){
//        this.ma_ctkm = ma_ctkm;
//    }
    public void initTableCTCTKM(){
        model = new DefaultTableModel();
        String []str = {"Mã Món","Tên Món","Giá gốc","Giá Giảm","Giá còn lại","Loại"};
        model.setColumnIdentifiers(str);
        tblCTCTKM.setModel(model);
    }
    public void loadTableCTCTKM(){
        cTChuongTrinhKMBLL.setListCTCTKM(model,this.getMaCTKM());
    }
    public void loadComboboxLoai(){
        model_1 = new DefaultComboBoxModel();
        loaiMonAnBLL.setTenLoaiToComboBox(model_1);
        cbLoaiOfKm.setModel(model_1);
    }
    public void loadComboboxMon(String ma_loai){
        model_2 = new DefaultComboBoxModel();
        monAnBLL.setMonAnToComboboxByMaLoai(model_2, ma_loai);
        cbxMonOfKm.setModel(model_2);
    }
    private void setNullCTCTKM() {
        txtTienGiam.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTenCTKM = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTCTKM = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnThemCTCTKM = new javax.swing.JButton();
        btnSuaCTCTMK = new javax.swing.JButton();
        btnDelCTCTKM = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cbLoaiOfKm = new javax.swing.JComboBox<>();
        cbxMonOfKm = new javax.swing.JComboBox<>();
        txtTienGiam = new javax.swing.JTextField();
        lblMaCTKM = new javax.swing.JLabel();

        lblTenCTKM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTenCTKM.setText("CHƯƠNG TRÌNH KHUYẾN MÃI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTenCTKM)
                .addGap(174, 174, 174))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblTenCTKM)
                .addContainerGap())
        );

        tblCTCTKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCTCTKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTCTKMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTCTKM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnThemCTCTKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_30px.png"))); // NOI18N
        btnThemCTCTKM.setText("Thêm món");
        btnThemCTCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTCTKMActionPerformed(evt);
            }
        });

        btnSuaCTCTMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_wrench_30px.png"))); // NOI18N
        btnSuaCTCTMK.setText("Sửa món");
        btnSuaCTCTMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCTCTMKActionPerformed(evt);
            }
        });

        btnDelCTCTKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa-30.png"))); // NOI18N
        btnDelCTCTKM.setText("Xóa");
        btnDelCTCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCTCTKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDelCTCTKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnThemCTCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaCTCTMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSuaCTCTMK, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnThemCTCTKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelCTCTKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbLoaiOfKm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLoaiOfKm.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại món"));
        cbLoaiOfKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiOfKmActionPerformed(evt);
            }
        });

        cbxMonOfKm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxMonOfKm.setBorder(javax.swing.BorderFactory.createTitledBorder("Món"));

        txtTienGiam.setBorder(javax.swing.BorderFactory.createTitledBorder("Tiền giảm"));

        lblMaCTKM.setBackground(new java.awt.Color(119, 122, 255));
        lblMaCTKM.setBorder(javax.swing.BorderFactory.createTitledBorder("Mã CTKM"));
        lblMaCTKM.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxMonOfKm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbLoaiOfKm, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaCTKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTienGiam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMaCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLoaiOfKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cbxMonOfKm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLoaiOfKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiOfKmActionPerformed
        String ten_loai = String.valueOf(cbLoaiOfKm.getSelectedItem());
        String ma_loai = loaiMonAnBLL.getMaLoaiByTenLoai(ten_loai);
        loadComboboxMon(ma_loai);
    }//GEN-LAST:event_cbLoaiOfKmActionPerformed

    private void btnThemCTCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTCTKMActionPerformed
        String []str = {
            lblMaCTKM.getText(),
            monAnBLL.getMaMonByTenMon(String.valueOf(cbxMonOfKm.getSelectedItem())),
            txtTienGiam.getText()
        };
        for(int i = 0 ; i < tblCTCTKM.getRowCount() ; i++){
            if(tblCTCTKM.getValueAt(i,0).equals(monAnBLL.getMaMonByTenMon((String)cbxMonOfKm.getSelectedItem()))){
                JOptionPane.showMessageDialog(this, "sản phẩm đã có trong chương trình khuyến mãi","Lỗi",JOptionPane.ERROR_MESSAGE);
                return;
            }   
        }
        cTChuongTrinhKMBLL.ThemCTCTKM(str);
        JOptionPane.showMessageDialog(this,"Thêm thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        loadTableCTCTKM();
        
        if(trang_thai == 1){    
            String ma_mon = monAnBLL.getMaMonByTenMon(String.valueOf(cbxMonOfKm.getSelectedItem()));
            int gia_giam = Integer.parseInt(txtTienGiam.getText());

            new MonAnBLL().suaGiaMonTheoKM(ma_mon,gia_giam);
            new AdminForm().load();
        }
        setNullCTCTKM();
    }//GEN-LAST:event_btnThemCTCTKMActionPerformed

    private void btnSuaCTCTMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCTCTMKActionPerformed
        String []str = {
            lblMaCTKM.getText(),
            monAnBLL.getMaMonByTenMon(String.valueOf(cbxMonOfKm.getSelectedItem())),
            txtTienGiam.getText()
        };
        cTChuongTrinhKMBLL.suaCTCTKM(str);
        JOptionPane.showMessageDialog(this,"Sửa thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        loadTableCTCTKM();
        
        if(trang_thai == 1){

            String ma_mon = monAnBLL.getMaMonByTenMon(String.valueOf(cbxMonOfKm.getSelectedItem()));
            int gia_giam = Integer.parseInt(txtTienGiam.getText());

            new MonAnBLL().suaGiaMonTheoKM(ma_mon,gia_giam);
            new AdminForm().load();
        }
        
        setNullCTCTKM();
    }//GEN-LAST:event_btnSuaCTCTMKActionPerformed

    private void btnDelCTCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCTCTKMActionPerformed
        int kq = JOptionPane.showConfirmDialog(this,"bạn có thật sự muốn xóa","Thông báo",JOptionPane.YES_OPTION);
        if(kq==0){
            int ma_ctkm = Integer.parseInt(lblMaCTKM.getText());
            String ma_mon = monAnBLL.getMaMonByTenMon(String.valueOf(cbxMonOfKm.getSelectedItem()));

            if(trang_thai == 1){

                int gia_giam = 0;

                new MonAnBLL().suaGiaMonTheoKM(ma_mon,gia_giam);
            }
            cTChuongTrinhKMBLL.delCTCTKM(ma_ctkm, ma_mon);
            loadTableCTCTKM();
            setNullCTCTKM();
        }
    }//GEN-LAST:event_btnDelCTCTKMActionPerformed

    private void tblCTCTKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTCTKMMouseClicked
        int click = tblCTCTKM.getSelectedRow();
        if(click >= 0){
            String ma_mon = String.valueOf(tblCTCTKM.getValueAt(click,0));
            
            CTChuongTrinhKMDTO cTChuongTrinhKMDTO = cTChuongTrinhKMBLL.getCtctkmByMaMon(ma_mon, ma_ctkm);
            System.out.println(ma_mon);
            System.out.println(ma_ctkm);
            if(cTChuongTrinhKMDTO != null){
                cbLoaiOfKm.setSelectedItem(cTChuongTrinhKMDTO.getTen_loai());
                cbxMonOfKm.setSelectedItem(cTChuongTrinhKMDTO.getTen_mon());
                txtTienGiam.setText(cTChuongTrinhKMDTO.getTien_giam()+"");
            }
        }
    }//GEN-LAST:event_tblCTCTKMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            //</editor-fold>
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CtkmForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CtkmForm(ma_ctkm,ten_ctkm,trang_thai).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelCTCTKM;
    private javax.swing.JButton btnSuaCTCTMK;
    private javax.swing.JButton btnThemCTCTKM;
    private javax.swing.JComboBox<String> cbLoaiOfKm;
    private javax.swing.JComboBox<String> cbxMonOfKm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaCTKM;
    private javax.swing.JLabel lblTenCTKM;
    private javax.swing.JTable tblCTCTKM;
    private javax.swing.JTextField txtTienGiam;
    // End of variables declaration//GEN-END:variables


}
